### ISSUE TITLE
Problem with current list -> str coercion in 2.0

### ISSUE THREAD

**Issue by achow0** [knight-lang/knight-lang#13]
In the 2.0 changelog, it says that the list -> str coercion will be the elements of the list joined by a newline. This seems fine at first glance, but it quickly becomes a huge issue for multi-dimensional lists like `[[1,2,3,4], [5,6,7,8]]`, or `+,+@1234,+@5678` in Knight code. When printing out this list of lists, what should happen? Well it would seem like an easy solution, just join the two inner lists together with a newline, right? But how will those inner lists be represented as a string? We will have to coerce them into strings as well, which means joining each element of those lists with a newline as well. This will ultimately cause an output like:
```
1
2
3
4
5
6
7
8
```
Or, a little better, something like this:
```
1
2
3
4

5
6
7
8
```
Even if the latter is outputted, I just feel like it will look clunky, ugly and somewhat confusing as well, especially as we get into higher dimension lists like 3d lists, where there could potentially be multiple newlines printed in a row. 

My suggestion is that we do something similar to python's `str()` when applied to lists, in that it coerces a list into a string in the form `[...]`, instead of using newlines, exactly how I wrote it earlier in the post (`O+@12345678` -> `[1,2,3,4,5,6,7,8]` and `O+,+@1234,+@5678` -> `[[1,2,3,4],[5,6,7,8]]`).

**Comment by sampersand** [comment]
I thought about that, but the problem is strings: Should `O"1, 2"` and `O+@"12"` convert to the same thing? Additionally, adding quotes wouldn't help, because `O+@(+"'" "'")` would end up clashing too.

Another alternative would be to simply require escaping `'` and `"`s in the resulting string. However, not every language has native escaping functionality, or even similar types (i.e. not everyhting escapes `'` via `\'`—some, like J, simply double it).

So, I thought the best of all bad choices would be to simply join every element via a newline, as that'd be ugly to represent in Knight natively. But I could be swayed. Another option would be to have the list join with no separator, so `O+@123` would write out `123`.
